---
- name: Add Jenkins apt repository key
  apt_key:
    url: "{{ jenkins_repo_key_url }}"

- name: Add Jenkins apt repository
  apt_repository:
    repo: "{{ jenkins_repo_url }}"

- name: Install apt packages for jenkins
  apt:
    name: "{{ item }}"
    state: present
    update_cache: "yes"
  with_items:
  - 'git'
  - 'jenkins'
  - 'sshpass'
  - 'python3-pip'
  - 'openjdk-8-jdk'

- name: Install ansible
  pip:
    name: ansible
    executable: "pip3"

- name: Restart jenkins
  service: name=jenkins state=restarted
  tags: jenkins_restart
