---
- name: Install python3, memcached packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python3-pip
    - memcached
    state: latest
  tags: apt

- name: Installing requirements.txt
  pip:
    requirements: '{{ requirements }}'
    executable: "pip3"
    state: forcereinstall
  tags: ['requirements', 'deploy']
  notify:
  - restart gunicorn


- name: Create directories
  file:
    path: '{{ site_root }}/whoosh_index'
    state: directory
    mode: 0777
