export const TO_DIALOG_VIEW = "TO_DIALOG_VIEW";
export const TO_DIALOG_LIST = "TO_DIALOG_LIST";
export const TO_DIALOG_CREATE = "TO_DIALOG_CREATE";
export const SAVE_DIALOG_LIST = "SAVE_DIALOG_LIST";
