- hosts: all

  roles:
  - nginx
  - postgresql

  vars_files:
  - 'vars.yml'

  become: yes
  gather_facts: no

  tasks:

  - name: Installing apt packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - git
        - python3-pip
        - memcached
      state: latest
    tags: apt

  - name: Clone repo
    git:
      repo: "{{ repository }}"
      dest: "{{ site_root }}"
      update: no
    when: "'prod' in group_names"
    tags: repo

  - name: Git pull origin dev
    git:
      repo: "{{ repository }}"
      dest: "{{ site_root }}"
      update: yes
      force: yes
      version: dev
    tags: ['never', 'git_pull']
    notify:
    - restart gunicorn

  - name: Installing requirements.txt
    pip:
      requirements: '{{ requirements }}'
      executable: "pip3"
      state: forcereinstall

  - name: Create directories
    file:
      path: '{{ site_root }}/whoosh_index'
      state: directory
      mode: 0777

  - name: Migrations
    command: python3 manage.py "{{ item }}" chdir="{{ site_root }}"
    with_items:
    - 'makemigrations'
    - 'migrate'
    tags: migrations

  - name: Gunicorn configuration
    template:
      src: etc/systemd/system/gunicorn.service
      dest: /etc/systemd/system/gunicorn.service
    notify:
    - restart gunicorn

  handlers:
  - name: restart gunicorn
    service:
      name: gunicorn
      state: restarted
