---
- name: Installing apt packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - postgresql
    - postgresql-contrib
    - python3-psycopg2
    state: latest
  tags: apt

  notify:
  - restart postgresql

- name: DB create
  become_user: postgres
  postgresql_db:
    name: '{{ db_name }}'
    encoding: UTF-8

- name: DB user create
  become_user: postgres
  postgresql_user:
    db: '{{ db_name }}'
    name: '{{ db_user }}'
    password: '{{ db_pass }}'
    priv: ALL
